# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barmetro', '0002_remove_mainpage_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='coord_metro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metroname', models.CharField(max_length=200)),
                ('langituge', models.TextField()),
                ('latitude', models.TextField()),
            ],
        ),
    ]
