# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barmetro', '0003_coord_metro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coord_metro',
            new_name='CoordMetro',
        ),
        migrations.RenameField(
            model_name='coordmetro',
            old_name='langituge',
            new_name='longitude',
        ),
    ]
