# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barmetro', '0004_auto_20170121_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barname', models.CharField(max_length=200)),
                ('longitude', models.TextField()),
                ('latitude', models.TextField()),
                ('address', models.TextField()),
                ('district', models.TextField()),
                ('area', models.TextField()),
                ('phone_number', models.TextField()),
            ],
        ),
    ]
