# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barmetro', '0005_coordbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordmetro',
            name='distance_1000',
            field=models.ManyToManyField(related_name='metro_1000', to='barmetro.CoordBar'),
        ),
        migrations.AddField(
            model_name='coordmetro',
            name='distance_300',
            field=models.ManyToManyField(related_name='metro_300', to='barmetro.CoordBar'),
        ),
        migrations.AddField(
            model_name='coordmetro',
            name='distance_500',
            field=models.ManyToManyField(related_name='metro_500', to='barmetro.CoordBar'),
        ),
    ]
