# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barmetro', '0006_auto_20170203_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordmetro',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
